### ISSUE TITLE
目前播放不了

### ISSUE THREAD

**Issue by kaich** [zhnnnnn/zhnbilibili#2]
非常不错，但是目前运行起来播放不了，希望作者看看！

**Comment by zhnnnnn** [comment]
嗯嗯，我有空看看

**Comment by zhnnnnn** [comment]
VideoURL类里面有两个获取播放url的方法，你切换一下看看。如果还是不能播放那就是不行了。。我也无能为力了，b站对播放链接做了一些处理的

**Comment by kaich** [comment]
@嗯嗯，我知道了，非常感谢啊！
